### ISSUE TITLE
Issue with AndroidX Navigation — User can't go back.

### ISSUE THREAD

**Issue by mikayelgr** [MichaelGrigoryan25/Nite#2]
## Issue Description:
After navigating from `HomeFragment` to `NewNoteFragment` the back button doesn't work when needed to navigate back. I think something has to be done with `MainActivity` also.

## Files Mentioned: 
[HomeFragment](https://github.com/MichaelGrigoryan25/Nite/blob/main/app/src/main/java/com/michaelgrigoryan/nite/ui/HomeFragment.kt), [NewNoteFragment](https://github.com/MichaelGrigoryan25/Nite/blob/main/app/src/main/java/com/michaelgrigoryan/nite/ui/NewNoteFragment.kt), [MainActivity](https://github.com/MichaelGrigoryan25/Nite/blob/main/app/src/main/java/com/michaelgrigoryan/nite/MainActivity.kt)

## Expected behavior: 
User should be returned back to the `HomeFragment`

## Current behavior: 
Neutral

**Comment by brijeshshah13** [comment]
Picked up

**Comment by brijeshshah13** [comment]
@MichaelGrigoryan25 This has been resolved by [this](https://github.com/MichaelGrigoryan25/Nite/commit/7051f647095b9e033641e80db9a30cd071907cc3) commit

**Comment by mikayelgr** [comment]
LGTM @brijeshshah13 !
