### ISSUE TITLE
App crashes when switching to Dark Mode

### ISSUE THREAD

**Issue by mikayelgr** [MichaelGrigoryan25/Nite#4]
When I tried switching to dynamic theming light theme worked fine but when I changed to night theme the app crashed. The changes have not been commited just to keep the main branch clean. Will push the updated version to development tommorow.

**Comment by brijeshshah13** [comment]
Will try to pick this up asap

**Comment by mikayelgr** [comment]
> Will try to pick this up asap

I have already traced the isssue. I forgot to add the values in `themes.xml` for dark mode

**Comment by mikayelgr** [comment]
Fixed in ee5648d
